### ISSUE TITLE
Store passwords encrypted

### ISSUE THREAD

**Issue by Maxxee** [google/samba-documents-provider#42]
Have a look in ServerCachePref.xml and be shocked. All passwords are stored there in plain text.
Professional coding...not by Google.

**Comment by ttanxu** [comment]
Fixed in pull #32.

Please note that full disk encryption is enabled for all N devices and there are other security measures in Android system. It's in particular suspicious that you have access to this private file. Possibly you've rooted your phone, and with root access granted to any user, we can never be sure what apps may do to these credentials. Please note it's also your responsibility to protect your own credentials.
